site_name: Micro Blog Documentation
site_description: Documentation for the Micro Blog project built with go-micro v5
site_author: Micro Blog Team
repo_url: https://github.com/micro/blog
repo_name: micro/blog

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Microservices: architecture/microservices.md
    - Communication: architecture/communication.md
  - Services:
    - Users Service: services/users.md
    - Posts Service: services/posts.md
    - Comments Service: services/comments.md
    - Web Service: services/web.md
  - Development:
    - Setup: development/setup.md
    - Running: development/running.md
    - Building: development/building.md
  - API:
    - REST API: api/rest.md
    - gRPC API: api/grpc.md
  - UI:
    - Static UI: ui/static.md