// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: posts/proto/posts.proto

package posts

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Posts service

type PostsService interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	// == Tags ==
	TagPost(ctx context.Context, in *TagPostRequest, opts ...client.CallOption) (*TagPostResponse, error)
	UntagPost(ctx context.Context, in *UntagPostRequest, opts ...client.CallOption) (*UntagPostResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...client.CallOption) (*ListTagsResponse, error)
}

type postsService struct {
	c    client.Client
	name string
}

func NewPostsService(name string, c client.Client) PostsService {
	return &postsService{
		c:    c,
		name: name,
	}
}

func (c *postsService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "Posts.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsService) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.name, "Posts.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "Posts.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "Posts.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Posts.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsService) TagPost(ctx context.Context, in *TagPostRequest, opts ...client.CallOption) (*TagPostResponse, error) {
	req := c.c.NewRequest(c.name, "Posts.TagPost", in)
	out := new(TagPostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsService) UntagPost(ctx context.Context, in *UntagPostRequest, opts ...client.CallOption) (*UntagPostResponse, error) {
	req := c.c.NewRequest(c.name, "Posts.UntagPost", in)
	out := new(UntagPostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsService) ListTags(ctx context.Context, in *ListTagsRequest, opts ...client.CallOption) (*ListTagsResponse, error) {
	req := c.c.NewRequest(c.name, "Posts.ListTags", in)
	out := new(ListTagsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Posts service

type PostsHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
	// == Tags ==
	TagPost(context.Context, *TagPostRequest, *TagPostResponse) error
	UntagPost(context.Context, *UntagPostRequest, *UntagPostResponse) error
	ListTags(context.Context, *ListTagsRequest, *ListTagsResponse) error
}

func RegisterPostsHandler(s server.Server, hdlr PostsHandler, opts ...server.HandlerOption) error {
	type posts interface {
		Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error
		Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
		Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
		TagPost(ctx context.Context, in *TagPostRequest, out *TagPostResponse) error
		UntagPost(ctx context.Context, in *UntagPostRequest, out *UntagPostResponse) error
		ListTags(ctx context.Context, in *ListTagsRequest, out *ListTagsResponse) error
	}
	type Posts struct {
		posts
	}
	h := &postsHandler{hdlr}
	return s.Handle(s.NewHandler(&Posts{h}, opts...))
}

type postsHandler struct {
	PostsHandler
}

func (h *postsHandler) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.PostsHandler.Create(ctx, in, out)
}

func (h *postsHandler) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.PostsHandler.Read(ctx, in, out)
}

func (h *postsHandler) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.PostsHandler.Update(ctx, in, out)
}

func (h *postsHandler) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.PostsHandler.Delete(ctx, in, out)
}

func (h *postsHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.PostsHandler.List(ctx, in, out)
}

func (h *postsHandler) TagPost(ctx context.Context, in *TagPostRequest, out *TagPostResponse) error {
	return h.PostsHandler.TagPost(ctx, in, out)
}

func (h *postsHandler) UntagPost(ctx context.Context, in *UntagPostRequest, out *UntagPostResponse) error {
	return h.PostsHandler.UntagPost(ctx, in, out)
}

func (h *postsHandler) ListTags(ctx context.Context, in *ListTagsRequest, out *ListTagsResponse) error {
	return h.PostsHandler.ListTags(ctx, in, out)
}
